spring:
  application:
    name: gulimall-member
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/gulimall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # nacos 服务发现地址
  redis:
    host: 192.168.125.129
    password: acid10837
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000
