spring:
  application:
    name: gulimall-product
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # nacos 服务发现地址
  jackson:
    default-property-inclusion: non_null # json化排除null字段
    date-format: yyyy-MM-dd HH:mm:ss
#    date-format: java.text.SimpleDateFormat
  thymeleaf:
    cache: true # 开发，关闭缓存
  redis:
    host: 192.168.125.129
    password: acid10837
  session:
    timeout: 30m
    store-type: redis
  cache:
    type: redis
    redis:
      time-to-live: 3600000  # ms
      key-prefix: CACHE_
      cache-null-values: true  # 开启 缓存空置防止缓存传透

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志，打印执行的sql语句
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto  # 主键自增
      logic-delete-value: 0 # 逻辑已删除值（默认1）
      logic-not-delete-value: 1 # 逻辑未删除值（默认0）
  type-handlers-package: com.chanris.gulimall.product.config.typeHandler
#      logic-delete-field: show_status

server:
  port: 10004
logging:
  level:
    com.chanris.gulimall: warn

gulimall:
  thread:
    coreSize: 30
    maxSize: 300
    keepAliveTime: 20