spring:
  application:
    name: gulimall-product
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # nacos 服务发现地址
  jackson:
    default-property-inclusion: non_null # json化排除null字段
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志，打印执行的sql语句
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto  # 主键自增
      logic-delete-value: 0 # 逻辑已删除值（默认1）
      logic-not-delete-value: 1 # 逻辑未删除值（默认0）
#      logic-delete-field: show_status

server:
  port: 10004