spring:
  application:
    name: gulimall-order
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # nacos 服务发现地址
  rabbitmq:
    host: 192.168.125.129
    port: 5672
    # publisher-confirms: true 过期的
    publisher-confirm-type: correlated # 新版： 确认消息已发送到交换机 选择确认类型未交互
    publisher-returns: true  # 开启 发送端消息抵达队列的确认
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual # 客户端手动确认
  main:
    allow-circular-references: true # 允许循环依赖
  thymeleaf:
    cache: false
  redis:
    host: 192.168.125.129
    password: acid10837
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000

gulimall:
  thread:
    coreSize: 30
    maxSize: 300
    keepAliveTime: 20
