spring.thymeleaf.cache=false

gulimall.thread.coreSize=20
gulimall.thread.maxSize=200
gulimall.thread.keepAliveTime=10

# RabbitMQ配置
spring.rabbitmq.host=192.168.125.129
spring.rabbitmq.port=5672
# 虚拟主机配置
spring.rabbitmq.virtual-host=/
# 开启发送端消息抵达Broker确认
# spring.rabbitmq.publisher-confirms=true
# 开启发送端消息抵达Queue确认
spring.rabbitmq.publisher-returns=true
# 只要消息抵达Queue，就会异步发送优先回调returnfirm
spring.rabbitmq.template.mandatory=true
# 手动ack消息，不使用默认的消费端确认
spring.rabbitmq.listener.simple.acknowledge-mode=manual

#支付宝相关的配置
alipay.app_id=9021000137664028
alipay.merchant-private-key=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCWvuep3XdedtsAS/VO+eMlAs3QkdsFzdQDbvkDKOQR3JhaazUYNkM13Uxo8RUKOFE+achvwC00gvOx4Qcw69Yt/llrfRnMvZMCfohoZLYcLgDP9pfTu6DhBr2ybgW3HPeeMXij27qnYfsZVF3lWafzTMZ37yIHq3AzNs8uiL/XmG6zji8HBMCP0kREkwlbH0WepPkcGh2aEGmE96YIkKTQF72wgiHYpRrAi/4WEvbIcYrFXDYJtei5tHnEs2H/m15fSNuwHKwT5Hd5lwQ0h0kaD6UBpe4WO3+43TzF9O0IHyKIB22wc3KLuoF1J3vKbhjNqj5NVEa9prUCo6h91WGxAgMBAAECggEAK2y9EYrRuy2j8tbuyJxlmaDQJzgNDwP3AjIym31pDdgtL0bY2auv+tFQFJ72P6ZviPoyGjcTDqB2kRRQ3P/jCAbQPY2hJACsW7iVlPUGHOIHq+DOZdkUBB7MAJ1/GfvHPRPlO9atU1B/ZBGQpuQH5KeGOMBzXiA9xxMP5cjQ8srqikbLFhEfngtfQrsGkn26lWO5+1kEZm6EkY15NXc2gWLgxNq88P2k8Ehn9cC8U8UzQvqJ5epotbWEVMYOnqotUjhJneGtB4FGpSwlxh4zzLwK9DK6n9I9+qAdsi5RD4XwdOVdXcSxX50vEnCVhiJgo41T+N0YHeNtGGW8uFgvjQKBgQD+OWKo7j6RzNr4z6i1yYPoO3bOywu3WfjX6LcHTbz+j2WQlruzezZFdZ5/5s/OJNhyF0qY3opAagkeHOY/+eplmlxEsE4CVrFnYbvuUchTLInnLtleNdBnD3Y+dyImSl/dKmlfIlTA8EdqbHyq2LMNfUhXmlCRzOFHYBWoioq6owKBgQCXzHmVhDUfI11NhDUJxJ2dYCpx3zg/xkGXYs+/3xEofSC+HYm2Rw0KA95Q4NzAkovAvZx/Xv4rKfuiBzRYuiok+69XYwWp7Su2FtCCZzNjZh0vKyWj7Ko1HMwGX0IIfvpMT4fsXlVhJr6K1AE1K5sx2kLozGlaZn37Cp3ghF8rmwKBgQDHvQiSF5Wbcit9H5K7OVflB4tiEE/lP9Buus3K9D4Qd1PiFTvmWWEbk7zzWsJcgcB5a2lV0EspLuZ4/VW+YDnUmEH0Sd0Qo1KBGl3QcfsFtlGnDL0F8xwJTTGnBG0VTowhNWhSsaOLb3181T3h8Z5Ec/F5uqmg1CsPrCN4J1m2JwKBgDvzcpVdWImKsv+5ViUcdM9BuqGscg+l4iPCz5/Mnn8qI/NRwSCvIPQyoOu6UxTvC6i8egFH6APuGcZdKAxeweRHTnGp1wPMenX4vrKxxXbdTmthlAUQpAxD6kQd/PtUAtB+nIT6oKe04I39uthf93QR6lj82iLs1ZZ/E+km/ls/AoGBAIkPITu195wltBBi6HGiA9FcYVeLZCKIpiqQehvSsnW+PvdfFjYXPEGx5TX3ZVYQZnJUKh3vlqEQWz969baMUhWLDOo42ChWsepUlbW61jDnvEwH0D0slU0AKPY/yvE7WzYcxA2Epb42MlioxEjB+u/R8d2frClspziRGJevCBiD
alipay.alipay_public_key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlr7nqd13XnbbAEv1TvnjJQLN0JHbBc3UA275AyjkEdyYWms1GDZDNd1MaPEVCjhRPmnIb8AtNILzseEHMOvWLf5Za30ZzL2TAn6IaGS2HC4Az/aX07ug4Qa9sm4Ftxz3njF4o9u6p2H7GVRd5Vmn80zGd+8iB6twMzbPLoi/15hus44vBwTAj9JERJMJWx9FnqT5HBodmhBphPemCJCk0Be9sIIh2KUawIv+FhL2yHGKxVw2CbXoubR5xLNh/5teX0jbsBysE+R3eZcENIdJGg+lAaXuFjt/uN08xfTtCB8iiAdtsHNyi7qBdSd7ym4Yzao+TVRGvaa1AqOofdVhsQIDAQAB
alipay.notify_url=http://hjl.mynatapp.cc/payed/notify
alipay.return_url=http://member.gulimall.com/memberOrder.html
alipay.sign_type=RSA2
alipay.charset=utf-8
alipay.gatewayUrl=https://openapi-sandbox.dl.alipaydev.com/gateway.do

