spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # nacos 服务发现地址
  thymeleaf:
    cache: false # 开发，关闭
  redis:
    host: 192.168.125.129
    password: acid10837
  session:
    store-type: redis
    timeout: 30m
server:
  port: 12000

logging:
  level:
    com.chanris.gulimall: warn