spring:
  cloud:
    gateway:
      routes:
        - id: gulimall-product
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        - id: gulimall-admin
          #  使用spring cloud loadbalancer  语法： lb:// + <微服务注册名称>
          uri: lb://gulimall-admin  # 坑点!!!!: uri不支持下划线
          predicates:
            - Path=/api/admin/**
          filters:
            # 重写uri  /api/admin => /admin
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        - id: gulimall-third-party
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        - id: gulimall-member
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        - id: gulimall-ware
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        # 注意：这个route 规则 需要放在最后面！
        # 请求接口： gulimall.com  nginx直接代理给网关，网关判断 如果/api/**就转交给对应的服务器，如果 满足域名，转交给对应的服务
        - id: gulimall-search-host
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com
        - id: gulimall-item-host
          uri: lb://gulimall-product
          predicates:
            - Host=item.gulimall.com
        - id: gulimall-auth-host
          uri: lb://gulimall-auth-server
          predicates:
            - Host=auth.gulimall.com
        - id: gulimall-index-host
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com
        - id: gulimall-cart-host
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com